In [62]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
%matplotlib inline

# import xgboost as xgb
from sklearn.metrics import mean_squared_error

# from xgboost import XGBRegressor
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import StratifiedKFold
from sklearn.ensemble import GradientBoostingRegressor, GradientBoostingClassifier

import seaborn as sns
from pycebox.ice import ice, ice_plot
from matplotlib.cm import seismic

# import sympy as sym
from sympy import *

In [63]:
x1,x2,x3,y = [],[],[],[]
N = 1000

for i in range(0,N):
    
    a = 2
    b = 5
    
    X1 = np.random.normal(0, 1, size = 1)
    X2 = np.random.uniform(-1, 1, size = 1)
    eps = np.random.normal(-1, 1, size = 1)
    
    Y = X1*np.random.beta(a, b, size = 1) - 0.3*X2
    
    x1.append(X1)
    x2.append(X2)
    
    y.append(Y)


In [64]:
y


[array([0.13676667]),
 array([0.42439786]),
 array([-0.14575775]),
 array([-0.45042164]),
 array([0.90227611]),
 array([0.07587778]),
 array([0.34067554]),
 array([-0.57427183]),
 array([0.13622761]),
 array([-0.21181664]),
 array([-0.154186]),
 array([-0.11378588]),
 array([0.00779531]),
 array([0.69060342]),
 array([-0.06110032]),
 array([0.0719829]),
 array([0.87963103]),
 array([0.17856529]),
 array([0.76079087]),
 array([0.94821235]),
 array([0.36777933]),
 array([-0.10484944]),
 array([0.22176246]),
 array([-0.12673842]),
 array([-1.12819451]),
 array([-0.36775866]),
 array([-0.34392671]),
 array([0.22497949]),
 array([-0.93347674]),
 array([-0.38750797]),
 array([0.18170713]),
 array([-0.12065238]),
 array([-0.01184872]),
 array([-0.01318619]),
 array([-0.30321616]),
 array([-0.0900332]),
 array([0.27352024]),
 array([-0.04280928]),
 array([-0.31798229]),
 array([-0.00481156]),
 array([0.30520693]),
 array([-0.21666966]),
 array([-0.00783224]),
 array([-0.60530847]),
 array([0.5

In [65]:
# yprime = np.array(yprime)
data = np.concatenate([x1,x2,y], axis = 1)
df = pd.DataFrame(data, columns=['X1','X2','Y'])

In [68]:
simulated_X = df[['X1','X2']]
simulated_y = df.Y

simulated_X.to_csv("../data/processed/simulated_lee/simulated_X",index=False)
simulated_y.to_csv("../data/processed/simulated_lee/simulated_y",index=False)

In [69]:
simulated_X

X1        X2
0    0.103129 -0.359429
1    1.498644 -0.158249
2    0.450521  0.732279
3   -0.896077  0.805959
4    1.980726 -0.735985
..        ...       ...
995  0.172554  0.747242
996  1.151053  0.862832
997  0.050584 -0.008455
998  1.871526  0.943660
999  1.896322 -0.338582

[1000 rows x 2 columns]